env:
  browser: true
  es2021: true
  node: true
extends:
  - standard
  - plugin:@typescript-eslint/recommended
  - plugin:vue/essential
  - plugin:vue/vue3-recommended
  - '@vue/typescript'
  # ESLint の設定を Prettier で上書きするため、最後の方に記述する
  - plugin:prettier/recommended
  - prettier/vue
  - prettier/@typescript-eslint
parserOptions:
  ecmaVersion: 12
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {}
ignorePatterns:
  - 'functions/lib/**'
  - 'src/nuxt.config.ts'
  - '*/node_modules/*'
  - '**/firebase-auth-sw.js'
  - '**/sw.js'