env:
  browser: true
  es2021: true
  node: true
extends:
  - standard
  - plugin:@typescript-eslint/recommended
  # ESLint の設定を Prettier で上書きするため、最後の方に記述する
  - 'plugin:prettier/recommended'
  - 'prettier/@typescript-eslint'
parserOptions:
  ecmaVersion: 12
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {}
ignorePatterns:
  - '**/sw.js'
  - 'functions/lib/**'